
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ykgixjxkzwmlobkmyfii.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlrZ2l4anhrendtbG9ia215ZmlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NTMxOTIsImV4cCI6MjA2MzEyOTE5Mn0.UuRN3xEOsMrzQFcyGy2Uj-RuEJjsTxkCw6k1GkI_Rfo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    autoRefreshToken: true,
    persistSession: true,
  }
});
